version: '3'
services:

  front-envoy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./front_svc/envoy_front_svc.yaml:/etc/envoy-config.yaml
    ports:
      - "9090:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'front-svc' --service-node 'front-svc' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  backend_svc_envoy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./backend_svc/envoy_backend_svc.yaml:/etc/envoy-config.yaml
    ports:
      - "8786:8786"
      - "8788:8788"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'backend-svc' --service-node 'backend-svc' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  backend_svc:
    image: grpc-svc:v1
    ports:
      - "8081:8081"
    environment:
      - GRPC_SERVER_PORT=5051
      - GRPC_CLIENT_HOST=backend_util_envoy
      - GRPC_CLIENT_PORT=5052
      - JSON_CLIENT_HOST=backend_util_envoy
      - JSON_SERVER_PORT=8081
      - JSON_CLIENT_PORT=8082

  backend_util_envoy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./backend_util/envoy_backend_util.yaml:/etc/envoy-config.yaml
    ports:
      - "8789:8789"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'backend-util' --service-node 'backend-util' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  backend_util:
    image: grpc-svc:v1
    ports:
      - "8082:8082"
    environment:
      - GRPC_SERVER_PORT=5052
      - GRPC_CLIENT_HOST=backend_svc_envoy
      - GRPC_CLIENT_PORT=5051
      - JSON_CLIENT_HOST=backend_svc_envoy
      - JSON_SERVER_PORT=8082
      - JSON_CLIENT_PORT=8081

  backend_client_envoy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./backend_client/envoy_backend_client.yaml:/etc/envoy-config.yaml
    ports:
      - "8790:8790"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'backend-client' --service-node 'backend-client' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  backend_client:
    image: grpc-svc:v1
    ports:
      - "8083:8083"
    environment:
      - GRPC_SERVER_PORT=5053
      - GRPC_CLIENT_HOST=backend_client_envoy
      - GRPC_CLIENT_PORT=5052
      - JSON_CLIENT_HOST=backend_client_envoy
      - JSON_SERVER_PORT=8083
      - JSON_CLIENT_PORT=8082