apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-svc
spec:
  host: backend-svc.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-util
spec:
  host: backend-util.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-client
spec:
  host: backend-client.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---